/**
 * Cube LUT tests: parsing `.cube` files, interpolating them, and grading the
 * cart's palette through one.
 *
 * The LUTs are generated by the test from a stated mapping, so every expectation
 * is that mapping applied to the input — an identity cube must return what it
 * was given, a channel-swapping cube must return the swap. That is stronger than
 * checking against captured numbers, because it holds at every input rather than
 * at the handful somebody happened to record.
 */

import { describe, expect, it } from "vitest";
import {
  CubeLutError,
  SpriteSheet,
  StubCartEngine,
  applyLut01,
  applyLutRgb,
  gradePalette,
  lutToBytes,
  parseCubeLut,
  type Rgb,
} from "@cartbox/editor";

/**
 * Write a `.cube` 3D LUT whose samples come from `map`. Red varies fastest,
 * which is the order the format specifies and the order the reader assumes.
 */
function writeCube(size: number, map: (r: number, g: number, b: number) => [number, number, number]): string {
  const lines = [`TITLE "generated"`, `LUT_3D_SIZE ${size}`, "DOMAIN_MIN 0 0 0", "DOMAIN_MAX 1 1 1"];
  const last = size - 1;
  for (let b = 0; b < size; b += 1) {
    for (let g = 0; g < size; g += 1) {
      for (let r = 0; r < size; r += 1) {
        lines.push(map(r / last, g / last, b / last).map((value) => value.toFixed(6)).join(" "));
      }
    }
  }
  return lines.join("\n");
}

const IDENTITY = (r: number, g: number, b: number): [number, number, number] => [r, g, b];
const SWAP_RED_BLUE = (r: number, g: number, b: number): [number, number, number] => [b, g, r];

/** A spread of inputs including the corners and several interior points. */
const PROBES: Array<[number, number, number]> = [
  [0, 0, 0],
  [1, 1, 1],
  [0.5, 0.5, 0.5],
  [0.13, 0.87, 0.42],
  [0.99, 0.01, 0.5],
  [0.25, 0.75, 0],
];

describe("parseCubeLut", () => {
  it("reads the size, title, domain and every sample row", () => {
    const lut = parseCubeLut(writeCube(3, IDENTITY));

    expect(lut.dimensions).toBe(3);
    expect(lut.size).toBe(3);
    expect(lut.title).toBe("generated");
    expect(lut.domainMin).toEqual([0, 0, 0]);
    expect(lut.domainMax).toEqual([1, 1, 1]);
    expect(lut.table.length).toBe(3 ** 3 * 3);
  });

  it("ignores comments and blank lines", () => {
    const decorated = writeCube(2, IDENTITY)
      .split("\n")
      .flatMap((line) => ["# a comment", "", line])
      .join("\n");

    expect(parseCubeLut(decorated).size).toBe(2);
  });

  it("reads a 1D curve as a per-channel table", () => {
    const lut = parseCubeLut(["LUT_1D_SIZE 4", "0 0 0", "0.25 0.25 0.25", "0.5 0.5 0.5", "1 1 1"].join("\n"));
    expect(lut.dimensions).toBe(1);
    expect(lut.size).toBe(4);
  });

  it("rejects a file with no size line", () => {
    expect(() => parseCubeLut("0 0 0\n1 1 1")).toThrow(CubeLutError);
  });

  it("rejects a row count that disagrees with the declared size", () => {
    const truncated = writeCube(3, IDENTITY).split("\n").slice(0, -1).join("\n");
    expect(() => parseCubeLut(truncated)).toThrow(/Expected 27 colour rows/);
  });

  it("rejects an unreadable row", () => {
    expect(() => parseCubeLut("LUT_3D_SIZE 2\nnot a colour")).toThrow(CubeLutError);
  });

  it("rejects a size outside what the format permits", () => {
    expect(() => parseCubeLut("LUT_3D_SIZE 1\n0 0 0")).toThrow(/between/);
  });

  it("rejects an inverted domain", () => {
    const inverted = writeCube(2, IDENTITY).replace("DOMAIN_MAX 1 1 1", "DOMAIN_MAX 0 1 1");
    expect(() => parseCubeLut(inverted)).toThrow(/DOMAIN_MAX/);
  });
});

describe("applyLut01", () => {
  it("returns its input unchanged through an identity cube, at any size", () => {
    for (const size of [2, 3, 5, 17]) {
      const lut = parseCubeLut(writeCube(size, IDENTITY));
      for (const [r, g, b] of PROBES) {
        const [outR, outG, outB] = applyLut01(lut, r, g, b);
        expect(outR, `size ${size}`).toBeCloseTo(r, 5);
        expect(outG, `size ${size}`).toBeCloseTo(g, 5);
        expect(outB, `size ${size}`).toBeCloseTo(b, 5);
      }
    }
  });

  it("applies a linear mapping exactly, because trilinear interpolation is exact on one", () => {
    const lut = parseCubeLut(writeCube(2, SWAP_RED_BLUE));
    for (const [r, g, b] of PROBES) {
      const [outR, outG, outB] = applyLut01(lut, r, g, b);
      expect(outR).toBeCloseTo(b, 5);
      expect(outG).toBeCloseTo(g, 5);
      expect(outB).toBeCloseTo(r, 5);
    }
  });

  it("interpolates between samples rather than snapping to them", () => {
    // A coarse cube: without interpolation, everything would land on one of
    // three levels per channel.
    const lut = parseCubeLut(writeCube(3, IDENTITY));
    const midpoint = applyLut01(lut, 0.4, 0.4, 0.4)[0];
    expect(midpoint).toBeGreaterThan(0);
    expect(midpoint).not.toBeCloseTo(0.5, 3);
    expect(midpoint).toBeCloseTo(0.4, 5);
  });

  it("clamps inputs outside the declared domain to its ends", () => {
    const lut = parseCubeLut(writeCube(3, IDENTITY));
    expect(applyLut01(lut, -1, 0.5, 2)[0]).toBeCloseTo(0, 5);
    expect(applyLut01(lut, -1, 0.5, 2)[2]).toBeCloseTo(1, 5);
  });

  it("maps a curve through a 1D LUT per channel", () => {
    // A curve that doubles the low half and holds at the top.
    const lut = parseCubeLut(["LUT_1D_SIZE 3", "0 0 0", "1 1 1", "1 1 1"].join("\n"));
    expect(applyLut01(lut, 0.25, 0.25, 0.25)[0]).toBeCloseTo(0.5, 5);
    expect(applyLut01(lut, 0.75, 0.75, 0.75)[0]).toBeCloseTo(1, 5);
  });
});

describe("gradePalette", () => {
  it("leaves the palette alone at zero strength", () => {
    const engine = new StubCartEngine();
    const sheet = new SpriteSheet(engine);
    const before = sheet.paletteRgb();
    const lut = parseCubeLut(writeCube(2, SWAP_RED_BLUE));

    expect(gradePalette(lut, before, 0)).toEqual(before);
  });

  it("at full strength, equals the LUT applied to each entry", () => {
    const engine = new StubCartEngine();
    const sheet = new SpriteSheet(engine);
    const before = sheet.paletteRgb();
    const lut = parseCubeLut(writeCube(2, SWAP_RED_BLUE));

    expect(gradePalette(lut, before, 1)).toEqual(before.map((color) => applyLutRgb(lut, color)));
  });

  it("blends toward the graded colour in between", () => {
    const lut = parseCubeLut(writeCube(2, SWAP_RED_BLUE));
    const palette: Rgb[] = [[200, 10, 40]];
    const [graded] = gradePalette(lut, palette, 0.5);
    const [full] = gradePalette(lut, palette, 1);

    for (let channel = 0; channel < 3; channel += 1) {
      const expected = Math.round(palette[0]![channel]! + (full![channel]! - palette[0]![channel]!) * 0.5);
      expect(graded![channel]).toBe(expected);
    }
  });

  it("survives a round trip through the real sheet's palette", () => {
    const engine = new StubCartEngine();
    const sheet = new SpriteSheet(engine);
    const lut = parseCubeLut(writeCube(2, SWAP_RED_BLUE));
    const original = sheet.paletteRgb();

    const applied = sheet.applyPalette(gradePalette(lut, original, 1));
    expect(applied).toBe(sheet.paletteSize);

    // Read back off the engine: every entry is its own red and blue swapped.
    sheet.paletteRgb().forEach((color, index) => {
      const source = original[index]!;
      expect(color[0]).toBe(source[2]);
      expect(color[1]).toBe(source[1]);
      expect(color[2]).toBe(source[0]);
    });
  });
});

describe("lutToBytes", () => {
  it("emits a cube of the LUT's own size, red varying fastest", () => {
    const size = 4;
    const lut = parseCubeLut(writeCube(size, IDENTITY));
    const packed = lutToBytes(lut);

    expect(packed.size).toBe(size);
    expect(packed.data.length).toBe(size ** 3 * 3);

    // Stepping one cell along red moves only the red byte.
    expect(packed.data[3]! - packed.data[0]!).toBeGreaterThan(0);
    expect(packed.data[4]).toBe(packed.data[1]);
    expect(packed.data[5]).toBe(packed.data[2]);
  });

  it("expands a 1D curve into a cube so consumers see one shape", () => {
    const lut = parseCubeLut(["LUT_1D_SIZE 3", "0 0 0", "0.5 0.5 0.5", "1 1 1"].join("\n"));
    const packed = lutToBytes(lut);
    expect(packed.data.length).toBe(packed.size ** 3 * 3);
  });
});
