/**
 * The offline bake of Lockout's light map: `npm run bake:lockout` runs this with
 * BAKE_LOCKOUT=1 and rewrites lockoutLightmap.generated.ts. Skipped otherwise
 * (a bake takes a while); lockout-lightmap.test.ts checks the stored bake still
 * matches the arena's geometry.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { bakeLockoutLightmap, bytesToBase64, encodeRgbaPng, layoutFingerprint, lockoutMapLayout } from "@cartbox/editor";

describe.skipIf(!process.env.BAKE_LOCKOUT)("baking Lockout's light map", () => {
  it("bakes the arena and stores the result", () => {
    const started = Date.now();
    const layout = lockoutMapLayout();
    const rgba = bakeLockoutLightmap();
    const png = encodeRgbaPng(rgba, layout.size, layout.size, { compress: true });
    const out = path.resolve(__dirname, "../packages/editor/src/model/lockoutLightmap.generated.ts");
    writeFileSync(
      out,
      `// Generated by \`npm run bake:lockout\` — do not edit. The Lockout arena's baked
// light map (see lightmap.ts and lockoutSeed.ts), and the fingerprint of the
// light-map layout it was baked for.
export const LOCKOUT_LIGHTMAP = {
  fingerprint: ${JSON.stringify(layoutFingerprint(layout))},
  png: ${JSON.stringify(bytesToBase64(png))},
} as const;
`,
    );
    console.log(`baked ${layout.size}² in ${((Date.now() - started) / 1000).toFixed(1)}s, ${png.length} bytes`);
    expect(png.length).toBeGreaterThan(0);
  }, 600_000);
});
