/**
 * The offline bake of Lockout's light probes (ENGINE_PARITY_ROADMAP.md EP9):
 * `npm run bake:lockout-probes` runs this with BAKE_LOCKOUT_PROBES=1 and
 * rewrites lockoutProbes.generated.ts. Skipped otherwise.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { bakeLockoutProbes, encodeLightProbes, layoutFingerprint, lockoutMapLayout } from "@cartbox/editor";

describe.skipIf(!process.env.BAKE_LOCKOUT_PROBES)("baking Lockout's light probes", () => {
  it("bakes the arena's probe grid and stores it", () => {
    const started = Date.now();
    const grid = bakeLockoutProbes();
    const stored = encodeLightProbes(grid);
    const out = path.resolve(__dirname, "../packages/editor/src/model/lockoutProbes.generated.ts");
    writeFileSync(
      out,
      `// Generated by \`npm run bake:lockout-probes\` — do not edit. The Lockout arena's
// baked light probes (see lightProbes.ts and lockoutSeed.ts), and the
// fingerprint of the light-map layout (the arena's geometry) they were baked for.
export const LOCKOUT_PROBES = {
  fingerprint: ${JSON.stringify(layoutFingerprint(lockoutMapLayout()))},
  probes: ${JSON.stringify(stored)} as null | { min: [number, number, number]; max: [number, number, number]; counts: [number, number, number]; data: string },
};
`,
    );
    console.log(`baked ${grid.counts.join("×")} probes in ${((Date.now() - started) / 1000).toFixed(1)}s`);
    expect(grid.values.length).toBeGreaterThan(0);
  }, 600_000);
});
