/**
 * The offline bake of the Forerunner kit's maps (I15): `npm run bake:lockout-kit`
 * runs this with BAKE_LOCKOUT_KIT=1 and rewrites lockoutKitMaps.generated.ts.
 * Skipped otherwise (a bake takes a few seconds); forerunner-kit.test.ts checks
 * the stored bake still fits the kit.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { bakeLockoutKit } from "@cartbox/editor";

describe.skipIf(!process.env.BAKE_LOCKOUT_KIT)("baking the Forerunner kit's maps", () => {
  it("bakes every piece and stores the result", () => {
    const started = Date.now();
    const maps = bakeLockoutKit();
    const out = path.resolve(__dirname, "../packages/editor/src/model/lockoutKitMaps.generated.ts");
    const body = Object.entries(maps)
      .map(([name, m]) => `  ${name}: {\n    fingerprint: ${JSON.stringify(m.fingerprint)},\n    occlusion: ${JSON.stringify(m.occlusion)},\n    relief: ${JSON.stringify(m.relief)},\n  },`)
      .join("\n");
    writeFileSync(
      out,
      `// Generated by \`npm run bake:lockout-kit\` — do not edit. The Forerunner kit's
// baked occlusion and relief maps (see textureBake.ts and lockoutSeed.ts), by
// piece, with the fingerprint of the laid-out mesh each was baked for.
export const LOCKOUT_KIT_MAPS: Readonly<Record<string, { readonly fingerprint: string; readonly occlusion: string; readonly relief: string }>> = {
${body}
};
`,
    );
    console.log(`baked ${Object.keys(maps).length} pieces in ${((Date.now() - started) / 1000).toFixed(1)}s`);
    expect(Object.keys(maps)).toEqual(["wall", "pillar", "floor"]);
  }, 600_000);
});
