/**
 * Baked-in cart catalog for the static "demo" build (src/lib/staticSite.ts).
 *
 * Mirrors the rows that scripts/seed*.mjs upsert into the `carts` table, with
 * cart binaries served from public/demo/carts/ (regenerated by
 * scripts/bake-demo-carts.mjs) instead of object storage. Pages read from this
 * catalog when `isStaticExport` is set; the Supabase-backed paths are untouched
 * otherwise.
 */

import type { CatalogEntry } from "./catalog";
import { runtimeForConsoleModel } from "./catalog";
import { withBasePath } from "./staticSite";

export interface DemoCart {
  id: string;
  title: string;
  slug: string;
  description: string;
  tags: string[];
  consoleModel: "classic" | "pro";
  priceCents: number;
  plays: number;
}

/** Ordered newest-first, matching the Browse page's created_at sort. */
export const DEMO_CARTS: readonly DemoCart[] = [
  {
    id: "00000000-0000-4000-8000-000000000012",
    title: "Gotta Catch 'Em All (Pro)",
    slug: "gotta-catch-em-all-pro",
    description:
      "The night-time monster hunt, remastered for the Pro console: 640x360, dynamic coloured lighting (moonlight, a lantern that follows you, glowing lamps), achievements and score. Art, map and sound made in the Cartbox editor.",
    tags: ["rpg", "pro", "lighting", "demo"],
    consoleModel: "pro",
    priceCents: 0,
    plays: 0,
  },
  {
    id: "00000000-0000-4000-8000-000000000011",
    title: "Gotta Catch 'Em All",
    slug: "gotta-catch-em-all",
    description:
      "A monster-catching overworld — explore, find creatures in the tall grass, and catch all three. Art, map and sound made in the Cartbox editor.",
    tags: ["rpg", "classic", "demo"],
    consoleModel: "classic",
    priceCents: 0,
    plays: 0,
  },
  {
    id: "00000000-0000-4000-8000-000000000010",
    title: "Neon City",
    slug: "neon-city",
    description:
      "A cyberpunk side-scroller on the Pro core: parallax skyline, emissive neon, wet-street light pools, and a screen-space puddle reflection.",
    tags: ["cyberpunk", "pro", "demo"],
    consoleModel: "pro",
    priceCents: 0,
    plays: 0,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    title: "Lantern (lit demo)",
    slug: "lantern-lit-demo",
    description:
      "A dark chamber and a warm lantern — carry the light through with the arrow keys while the auto-detect lighting relights the frame around it.",
    tags: ["demo", "lighting"],
    consoleModel: "classic",
    priceCents: 0,
    plays: 0,
  },
  {
    id: "00000000-0000-4000-8000-000000000001",
    title: "Ring Runner (demo)",
    slug: "ring-runner-demo",
    description: "Hold right to raise the score; unlock First Blood at 30.",
    tags: ["demo"],
    consoleModel: "classic",
    priceCents: 0,
    plays: 0,
  },
];

/** Cart id used for the editable scratch cart in demo mode (localStorage-backed). */
export const DEMO_DRAFT_CART_ID = "draft";

/**
 * Ordering anchor for the demo build's unified Browse grid.
 *
 * Demo carts carry no timestamp — the array is simply ordered newest-first — but
 * merging them with demo titles needs a comparable date. Synthesising one per
 * index off a fixed epoch preserves the authored order and keeps the static
 * build deterministic, which a `Date.now()`-relative scheme would not.
 */
const DEMO_CART_EPOCH_MS = Date.parse("2026-07-14T00:00:00.000Z");
const DEMO_CART_SPACING_MS = 24 * 60 * 60 * 1000;

/** Adapts a baked-in demo cart to the unified catalog view model. */
export function demoCartToEntry(cart: DemoCart, index: number): CatalogEntry {
  return {
    kind: "cart",
    id: cart.id,
    name: cart.title,
    description: cart.description,
    runtime: runtimeForConsoleModel(cart.consoleModel),
    priceCents: cart.priceCents,
    plays: cart.plays,
    thumbUrl: demoThumbUrl(cart.id),
    href: `/play/${cart.id}`,
    createdAt: new Date(DEMO_CART_EPOCH_MS - index * DEMO_CART_SPACING_MS),
  };
}

export function findDemoCart(cartId: string): DemoCart | undefined {
  return DEMO_CARTS.find((cart) => cart.id === cartId);
}

/** Public URL of a demo cart's .tic binary, honouring the site base path. */
export function demoCartUrl(cartId: string): string {
  return withBasePath(`/demo/carts/${cartId}.tic`);
}

/**
 * Public URL of a demo cart's cover-art thumbnail (rendered by
 * scripts/bake-demo-thumbs.mjs), honouring the site base path. The static demo
 * build has no render worker, so these PNGs stand in for the covers the worker
 * would otherwise produce — used on the cartridge grid label and the feed card.
 */
export function demoThumbUrl(cartId: string): string {
  return withBasePath(`/demo/thumbs/${cartId}.png`);
}
